name: Deploy Site on push
on:
  push:
    branches:
      - main
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Get the latest code
      uses: actions/checkout@main
    - uses: actions/setup-node@main
    - name: Installing project dependencies
      run: npm install
    - name: Building the project
      run: npm run build
    - name: Zip build directory
      run: zip -r build.zip .
    - name: Upload bundle
      uses: bayssmekanique/action-simple-file-upload@master
      with:
        user: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        host: ${{ secrets.FTP_SERVER }}
        src: ./build.zip
        dest: build.zip
