name: Deploy Site on push
on:
  push:
    branches:
      - main
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Get the latest code
      uses: actions/checkout@main
    - uses: actions/setup-node@main
    - name: Installing project dependencies
      run: npm install
    - name: Building the project
      run: npm run build
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@vmaster
      with:
        server: ${{ secrets.FTP_SERVER}}
        username: ${{ secrets.FTP_USERNAME}}
        password: ${{ secrets.FTP_PASSWORD}}
